# Generated by Django 3.2.9 on 2022-01-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('desc_uz', models.TextField(blank=True, null=True)),
                ('desc_ru', models.TextField(blank=True, null=True)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=80, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=80, null=True)),
                ('name_en', models.CharField(blank=True, max_length=80, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('step', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('desc_uz', models.TextField(blank=True, null=True)),
                ('desc_ru', models.TextField(blank=True, null=True)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('cr_up', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.categories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('desc_uz', models.TextField(blank=True, null=True)),
                ('desc_ru', models.TextField(blank=True, null=True)),
                ('desc_en', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('cr_up', models.DateTimeField(auto_now=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.products')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_n', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('summa', models.IntegerField(default=0)),
                ('l_order_item', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('cr_on', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.users')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('amount', models.CharField(blank=True, max_length=80, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('summa', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.orders')),
                ('product_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.productitem')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.users')),
            ],
        ),
    ]
