# Generated by Django 3.2.9 on 2021-11-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20211126_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
