# Generated by Django 3.2.9 on 2021-11-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_users_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
