# Generated by Django 3.2.9 on 2021-12-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20211201_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
